### ISSUE TITLE
install trouble with auth

### ISSUE THREAD

**Issue by persianphilosopher** [ncarlier/nunux-reader#7]
Hi there,
I think I carefully followed your instructions (on a server, not on docker) except I don't have it run on /opt. I don't know if that is the problem but when I try to run the server, I always get the following error:

`> nunux-reader@1.0.0 start /var/www/nux
> node server/app | bunyan

connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0

/var/www/nux/server/security/index.js:23
  passport.serializeUser(function(user, done) {

TypeError: Cannot call method 'serializeUser' of undefined
    at module.exports (/var/www/nux/server/security/index.js:23:12)
    at Object.<anonymous> (/var/www/nux/server/app.js:86:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3`

Any hint would be appreciated

**Comment by ncarlier** [comment]
Hello,

it is weird!?! According to the error `passport ` the lib used to manage authentication is not correctly loaded by the app. What is your version of node and npm?

```bash
node --version
npm --version
```

Can you check that you have valid distribution of passport inside the node_modules:

```bash
cat node_modules/passport/package.json
```
Mine is: "version": "0.1.18"

Can you retry a dependency installation:  `rm -rf node_modules && npm install`

**Comment by persianphilosopher** [comment]
Thank you so much for getting back to me.
I also have 0.1.18 for passport. 
node -v : v6.10.2
npm -v: 3.10.10

I removed the modules and reinstalled (even removed npm and node and again reinstalled) and still face the same obstacle:

> nunux-reader@1.0.0 start /var/www/nux
> node server/app | bunyan

connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
/var/www/nux/server/security/index.js:23
  passport.serializeUser(function(user, done) {
  

TypeError: Cannot read property 'serializeUser' of undefined
    at module.exports (/var/www/nux/server/security/index.js:23:11)
    at Object.<anonymous> (/var/www/nux/server/app.js:86:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

Sorry for the trouble

**Comment by ncarlier** [comment]
I have exactly same versions.
Can you provide me the result of the `npm install`. Maybe NPM alert you on a pb during the installation,
Can you also show me the output of this command: `env | grep APP_`
Are you on a amd64, 32bit or ARM linux distribution?

**Comment by persianphilosopher** [comment]
I think you are onto the problem. Even though I have sourced the /etc/default/dev.env, env | grep returns nothing.
I am on amd64.
[Here is the output of npm and the results](https://pastebin.com/R8ZZBSCP)

**Comment by ncarlier** [comment]
Output seems to be ok.
In therory the app is working without env configuration. There is a default configuration.
Except for Google auth provider. It should fail claiming the OAuth key and secret. But the error is different.
Can you try to export individually env vars if source don't work. You can also try to load the file with: `. ./etc/default/dev.env`.
The only thing I see after that is to insert log inside the code.
You ca try to add the following line:
```
console.log(passport)
```
Before: https://github.com/ncarlier/nunux-reader/blob/master/server/app.js#L86
And before: https://github.com/ncarlier/nunux-reader/blob/master/server/security/index.js#L22
