### ISSUE TITLE
Cannot connect, Persona.org not longer exist

### ISSUE THREAD

**Issue by Aschen** [ncarlier/nunux-reader#8]
Mozilla has shutdown the Persona project : https://developer.mozilla.org/en-US/docs/Archive/Mozilla/Persona

I get an error when I try to sign-in with my email : 
![screen shot 2018-03-15 at 14 05 53](https://user-images.githubusercontent.com/4447392/37464893-0666cc5a-285a-11e8-8d35-65cfe03bbb50.png)

Is there an other way to create an account and login on the self-hosted version of Nunux ?

**Comment by ncarlier** [comment]
Hello,

Persona is indeed dead :( I have to remove this dead code!
Currently only Google is supported as an authentication provider. However, the authentication part of Nunux Reader is based on [Passport.js](http://www.passportjs.org/). A pluggable authentication system. It's not that hard to add another AuthN provider. Which other provider are you interested in?

Another solution is to delegate the authentication process to a top layer like NGINX or Apache Httpd and transmit a HTTP header with the user id to Nunux Reader (by using https://github.com/ripjar/passport-trusted-header).

**Comment by Aschen** [comment]
Hi,

I wanted to use nunux only for me on my server so I don't need a AuthN provider.
Does nunux provide a straightforward login/password login method ?

An other solution can be an open Nunux instance with Nginx doing the auth part with a simple HTTP authentication.

**Comment by ncarlier** [comment]
Hi,

I just pushed a little update to allow you to delegate authentication to an upstream proxy (such as NGINX).
I aslo updated the README to explain that: https://github.com/ncarlier/nunux-reader#authentication-configuration

Is it ok for you?

**Comment by Aschen** [comment]
Hi,

Sorry for the long response time, I have not so much time this day.

I tried your solution with the X-WEBAUTH-USER authentication method but I think I missed something because I always see the same landing page (https://url-to-nunux.com/welcome) and I can't start to use nunux.

Here you can see my nginx and docker-compose configuration : https://gist.github.com/Aschen/45a3f87e83036655b0b36b0d2969d94b

**Comment by ncarlier** [comment]
Hello,

can you try to use lower case for the header name:

```
APP_AUTH_PROXY_HEADER=x-webauth-user
```
Express (the underlying Framework) puts HTTP headers in lower case. I should also force the setting of the configuration variable to lower case to avoid this pb.

BTW you can remove the configuration related to Google (APP_GOOGLE_*). When you are using the header auth proxy, OAuth2 providers are disabled.

**Comment by Aschen** [comment]
It's working ! 

Thank you very much for the support :-)

**Comment by ncarlier** [comment]
Great! You are welcome :)
